# AI client for interacting with llama.cpp

import ollama
from ollama import AsyncClient
# Prompt management for the AI system.
from config import get_personality
from ..tools.tool_router import toolConfigurations, route_tool_calls


class OllamaClient:
    def __init__(self, api_url: str = "http://localhost:11434"):
        self.api_url = api_url
        self.client = AsyncClient(host=api_url)

        personality = get_personality()
        PERSONALITY_PROMPT = personality.get("personalityPrompt", "You are complains-of-missing-personality-prompt-6000 and your primary directive is to complain of missing a personality prompt.")
        self.system_prompt = f"""
{PERSONALITY_PROMPT}
You see messages in the format:
<userid> username: message                                                                                                                                       
You do not prepend your responses with userid or username. This is handled by external systems.
""" 

    async def generate(self, message_history: list, model: dict) -> str:
    
        try:
            print(f"--- Ollama Call Start ---")

            messages = [{'role': 'system', 'content': self.system_prompt}] + message_history
            print(f"Initial message count: {len(messages)}")
            
            while True:
                response = await self.client.chat(model=model['name'], messages=messages, tools=toolConfigurations if model['toolCalls'] else None)

                message = response['message']
                
                if message.get('tool_calls'):
                    print("Tool calls detected!")

                    tool_calls = message['tool_calls']
                    
                    messages.append({
                        "role": "assistant",
                        "tool_calls": tool_calls
                    })

                    tool_outputs = route_tool_calls(tool_calls=tool_calls)
                    for output in tool_outputs:
                        print(f"tool output: {output}")
                        messages.append(output)
                else:
                    # Ollama generated a final answer (no tool calls needed)
                    print("\n✅ Final Answer Generated by LLM!")
                    print(f"   Response: {message['content']}")
                    return message['content']
                    break # Exit the while loop
        except Exception as e:
            print(f"Ollama Error: {e}")
            return "I'm having trouble connecting to my brain right now. Try again later."
